###
@hostname = localhost 
@port = 5101 
@host = https://{{hostname}}:{{port}} 
@contentType = application/json

### 
GET {{host}}/api/users

### 
GET {{host}}/api/users/2

### 
POST {{host}}/api/users 
Content-Type: {{contentType}}
{
    "id": 0,
    "firstName": "First Name Test 0", 
    "lastName": "Last Name Test 0"
}

### 
POST {{host}}/api/users 
Content-Type: {{contentType}}
{
    "id": 2,
    "firstName": "First Name Test 2", 
    "lastName": "Last Name Test 2"
}

### 
PUT {{host}}/api/users/2
Content-Type: {{contentType}}
{
    "id" : 2,
    "firstName": "TesterFirst", 
    "lastName": "TesterLast"
}

### 
DELETE {{host}}/api/users/0

### 
DELETE {{host}}/api/users/2